apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: ibm-spectrum-scale
  app.kubernetes.io/name: operator

namespace: ibm-spectrum-scale-operator
namePrefix: ibm-spectrum-scale-

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- digest: sha256:85fb826bdafff98bac9046001f8fb6e8dd5da67c2322b12b2e436ba86ff3d99a
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator

components:
- ../../components/rbac/deploy
- ../../components/rbac/regionaldr
- ../../components/rbac/gui
- ../../components/webhook/deploy
- ../../components/manager/deploy
