apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: ibm-spectrum-scale
  app.kubernetes.io/name: operator

namespace: ibm-spectrum-scale-operator
namePrefix: ibm-spectrum-scale-

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- digest: sha256:9a87ce8dda3d461eb48fc47f6b7c7e43e31f64918acd68cc5c89818e8a1fe309
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator

components:
- ../../components/rbac/deploy
- ../../components/rbac/regionaldr
- ../../components/rbac/gui
- ../../components/webhook/deploy
- ../../components/manager/deploy
