apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: ibm-spectrum-scale
  app.kubernetes.io/name: operator

namespace: ibm-spectrum-scale-operator
namePrefix: ibm-spectrum-scale-

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- digest: sha256:1a7ebdb5bd32042699ccb3881f50da8f75f717989235204cf464a6d7e0d27ab9
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator

components:
- ../../components/rbac/deploy
- ../../components/rbac/regionaldr
- ../../components/rbac/gui
- ../../components/webhook/deploy
- ../../components/manager/deploy
