apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Uncomment to enable conversion webhook
#patches:
#  - patches/webhook_in_daemons.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# Uncomment to enable certmanager injection for conversion webhook
#- patches/cainjection_in_daemons.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
resources:
- scale.spectrum.ibm.com_approvalrequests.yaml
- scale.spectrum.ibm.com_asyncreplications.yaml
- scale.spectrum.ibm.com_callhomes.yaml
- scale.spectrum.ibm.com_cloudcsidisks.yaml
- scale.spectrum.ibm.com_clusterinterconnects.yaml
- scale.spectrum.ibm.com_clusters.yaml
- scale.spectrum.ibm.com_compressionjobs.yaml
- scale.spectrum.ibm.com_consistencygroups.yaml
- scale.spectrum.ibm.com_daemons.yaml
- scale.spectrum.ibm.com_diskjobs.yaml
- scale.spectrum.ibm.com_dnsconfigs.yaml
- scale.spectrum.ibm.com_dnss.yaml
- scale.spectrum.ibm.com_encryptionconfigs.yaml
- scale.spectrum.ibm.com_filesystems.yaml
- scale.spectrum.ibm.com_grafanabridges.yaml
- scale.spectrum.ibm.com_guis.yaml
- scale.spectrum.ibm.com_localdisks.yaml
- scale.spectrum.ibm.com_pmcollectors.yaml
- scale.spectrum.ibm.com_recoverygroups.yaml
- scale.spectrum.ibm.com_regionaldrexports.yaml
- scale.spectrum.ibm.com_regionaldrs.yaml
- scale.spectrum.ibm.com_remoteclusters.yaml
- scale.spectrum.ibm.com_restripefsjobs.yaml
- scale.spectrum.ibm.com_stretchclusterinitnodes.yaml
- scale.spectrum.ibm.com_stretchclusters.yaml
- scale.spectrum.ibm.com_stretchclustertiebreakers.yaml
- scale.spectrum.ibm.com_upgradeapprovals.yaml
- scale.spectrum.ibm.com_volumes.yaml
